on:
  push:
    branches:
      - master
name: Deploy to Github Pages
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout
      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll
          echo "blog.garrit.xyz" > CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: out
