on:
  push:
    branches:
      - master
name: Deploy to Github Pages
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          BUILD_SCRIPT: npm ci && npm run build && touch out/.nojekyll
          CNAME: blog.garrit.xyz
